package com.bca.core_banking_service.dto;

import java.net.URI;
import java.util.Objects;
import com.bca.core_banking_service.dto.AccountType;
import com.bca.core_banking_service.dto.CheckingAccountResponse;
import com.bca.core_banking_service.dto.FixedTermAccountResponse;
import com.bca.core_banking_service.dto.PymeCheckingAccountResponse;
import com.bca.core_banking_service.dto.SavingsAccountResponse;
import com.bca.core_banking_service.dto.VipSavingsAccountResponse;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import jakarta.annotation.Generated;


@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = CheckingAccountResponse.class, name = "CHECKING"),
  @JsonSubTypes.Type(value = FixedTermAccountResponse.class, name = "FIXED_TERM"),
  @JsonSubTypes.Type(value = PymeCheckingAccountResponse.class, name = "PYME_CHECKING"),
  @JsonSubTypes.Type(value = SavingsAccountResponse.class, name = "SAVINGS"),
  @JsonSubTypes.Type(value = VipSavingsAccountResponse.class, name = "VIP_SAVINGS"),
  @JsonSubTypes.Type(value = CheckingAccountResponse.class, name = "CheckingAccountResponse"),
  @JsonSubTypes.Type(value = FixedTermAccountResponse.class, name = "FixedTermAccountResponse"),
  @JsonSubTypes.Type(value = PymeCheckingAccountResponse.class, name = "PymeCheckingAccountResponse"),
  @JsonSubTypes.Type(value = SavingsAccountResponse.class, name = "SavingsAccountResponse"),
  @JsonSubTypes.Type(value = VipSavingsAccountResponse.class, name = "VipSavingsAccountResponse")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-16T18:51:45.932800-05:00[America/Lima]")
public interface AccountPolymorphicResponse {
    public AccountType getType();
}
